### ISSUE TITLE
Colourblindness options

### ISSUE THREAD

**Issue by SsbThatsMe** [Willenbrink/Ivis-project#23]
The most common type of colourblindness is red-green colourblindness. Currently, we show whether a country has a greater or lesser value than the selected one by colouring it either red or green (in "PerCategoryViz"). This would be problematic for many individuals. We should have an option somewhere to toggle the colours that are used in the visualisation.

**Comment by vlle1** [comment]
Yes. Please don't open up feature-issues independently of the current scope ( MVP ) - see the viz_spec. It is planned at a later stage.
