### ISSUE TITLE
Bug: Age Category with invisible extremum

### ISSUE THREAD

**Issue by Willenbrink** [Willenbrink/Ivis-project#38]
When selecting Age category and France no country is bluer. The legend tells otherwise. There is likely some city-state that has a higher value but is not shown. We should either show every state or remove the invisible ones from the data set.

**Comment by SsbThatsMe** [comment]
That would be due to our map detail level I believe. Since we're not using a super-detailed map for the sake of not tanking our performance some island nations and similar are not being shown. We'll have to look into ways of including them before the final version is made.

**Comment by vlle1** [comment]
see #50
